import Head from 'next/head'
import Link from 'next/link'
import StoreCard from '../components/StoreCard'
import { ConnectButton } from '@rainbow-me/rainbowkit';
import styles from '../styles/Home.module.css'

export default function Home() {

  const stores = Array(8).fill({
    img:'https://ugtechmag.com/wp-content/uploads/2020/04/Odukar-Store-ugtechmag.jpeg',
    description:'Electronics devices',
    name:'TMP store'
  })

  return (
    <div>
      <Head>
        <title>Dree store | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <nav>
            <img src="https://blog.hubspot.com/hubfs/ecommerce-software.jpg" alt="" />
            <ConnectButton accountStatus="avatar" chainStatus="icon" showBalance={false}/>
          </nav>
          <div className={styles.caroussel}>
            <section>
              <p>Shop on the decentralized web</p> 
              <Link href='/create-store'>New store</Link>
            </section>
            <img src="https://alahausse.ca/wp-content/uploads/2021/08/giphy-phone.gif" alt="" />
          </div>
        </div>
        <div>
          <div className={styles.categories}>
            <span>Categories</span>
            <section>
              <button>Electronics</button>
              <button>Clothes</button>
              <button>Shoes</button>
              <button>Photography</button>
              <button>Others</button>
            </section>
          </div>
          <div className={styles.stores}>
            {stores?.map(({img, description, name}) => <StoreCard key={3} id={20} img={img} description={description} name={name} />)}
          </div>
        </div>
      </main>
    </div>
  )
}
