import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dree store | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <nav>
            <img src="https://blog.hubspot.com/hubfs/ecommerce-software.jpg" alt="" />
            <button>Connect wallet</button>
          </nav>
          <div className={styles.caroussel}>
            <section>
              <p>Shop on the decentralized web</p> 
              <a href="">Start now</a>
            </section>
            <img src="/images/dree-store.gif" alt="" />
          </div>
        </div>
        <div>
          <div className={styles.categories}>
            <span>Categories</span>
            <section>
              <button>Electronics</button>
              <button>Clothes</button>
              <button>Shoes</button>
              <button>Photography</button>
              <button>Others</button>
            </section>
          </div>

        </div>
      </main>
    </div>
  )
}
